# Generated by Django 5.2.12 on 2026-04-15 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coordinates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toll', to='common.coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='TollCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(blank=True, max_length=20)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('lane_identifier', models.CharField(blank=True, max_length=20)),
                ('toll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='tolls.toll')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TollConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('max_speed_kph', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maps_distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('maps_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('maps_duration_in_traffic_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('maps_last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('from_toll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='tolls.toll')),
                ('to_toll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='tolls.toll')),
            ],
        ),
        migrations.CreateModel(
            name='TollConnectionDailyTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expected_duration_seconds', models.PositiveIntegerField()),
                ('expected_duration_in_traffic_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='maps_distance_matrix', max_length=40)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_times', to='tolls.tollconnection')),
            ],
        ),
        migrations.CreateModel(
            name='TollTraversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_duration_seconds', models.PositiveIntegerField()),
                ('expected_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('average_speed_kph', models.FloatField(blank=True, null=True)),
                ('is_speeding', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traversals', to='tolls.tollconnection')),
                ('entry_capture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_entry', to='tolls.tollcapture')),
                ('exit_capture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_exit', to='tolls.tollcapture')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traversals', to='vehicles.vehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='tollcapture',
            index=models.Index(fields=['toll', 'captured_at'], name='tolls_tollc_toll_id_bbb3ab_idx'),
        ),
        migrations.AddIndex(
            model_name='tollcapture',
            index=models.Index(fields=['plate_text', 'captured_at'], name='tolls_tollc_plate_t_4f958e_idx'),
        ),
        migrations.AddConstraint(
            model_name='tollconnection',
            constraint=models.UniqueConstraint(fields=('from_toll', 'to_toll'), name='unique_toll_connection'),
        ),
        migrations.AddIndex(
            model_name='tollconnectiondailytime',
            index=models.Index(fields=['connection', 'date'], name='tolls_tollc_connect_00eba6_idx'),
        ),
        migrations.AddConstraint(
            model_name='tollconnectiondailytime',
            constraint=models.UniqueConstraint(fields=('connection', 'date'), name='unique_connection_daily_time'),
        ),
    ]
