# Generated by Django 5.2.12 on 2026-05-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0002_roadeye_backend_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tollconnectiondailytime',
            name='connection',
        ),
        migrations.RemoveIndex(
            model_name='tollcapture',
            name='tolls_tollc_plate_t_4f958e_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='tolls_audit_entity__3dda1d_idx',
            old_name='tolls_audit_entity__74bc25_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='tolls_audit_action_a9b7d4_idx',
            old_name='tolls_audit_action_66d27f_idx',
        ),
        migrations.RenameIndex(
            model_name='fine',
            new_name='tolls_fine_status_d5acee_idx',
            old_name='tolls_fine_status_8d24f1_idx',
        ),
        migrations.RenameIndex(
            model_name='fine',
            new_name='tolls_fine_referen_19ca59_idx',
            old_name='tolls_fine_referen_8af083_idx',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='due_at',
        ),
        migrations.RemoveField(
            model_name='toll',
            name='city',
        ),
        migrations.RemoveField(
            model_name='toll',
            name='road_name',
        ),
        migrations.RemoveField(
            model_name='tollcapture',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='tollcapture',
            name='lane_identifier',
        ),
        migrations.RemoveField(
            model_name='tollcapture',
            name='ocr_confidence',
        ),
        migrations.RemoveField(
            model_name='tollcapture',
            name='raw_ocr_payload',
        ),
        migrations.RemoveField(
            model_name='tollconnection',
            name='maps_distance_meters',
        ),
        migrations.RemoveField(
            model_name='tollconnection',
            name='maps_duration_in_traffic_seconds',
        ),
        migrations.RemoveField(
            model_name='tollconnection',
            name='maps_duration_seconds',
        ),
        migrations.RemoveField(
            model_name='tollconnection',
            name='maps_last_synced_at',
        ),
        migrations.RemoveField(
            model_name='tollconnection',
            name='tolerance_kph',
        ),
        migrations.AddField(
            model_name='tollconnection',
            name='allowed_time_minutes',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='TollConnectionDailyTime',
        ),
    ]
